### ISSUE TITLE
XP bar improvement

### ISSUE THREAD

**Issue by Goblin-aka-Dark** [s7092910/Quartz#21]
I was told that to achieve the goal Harmony is needed, but it might be possible via Quartz.

![image](https://github.com/s7092910/Quartz/assets/162380803/abb0038d-4c90-4481-906a-44204cab0a26)

I would like that so when the maximum level is reached, the value **to next level** is = 0. At the moment the value is simply duplicated from level 299.

![image](https://github.com/s7092910/Quartz/assets/162380803/b80995b5-6e80-4e84-a2db-5764e7fc0fa1)

I would like it to be like this or something more "informative" to mean “the maximum has been reached”
![image](https://github.com/s7092910/Quartz/assets/162380803/ca1bb115-c437-4ee4-b7f3-803be2ecd2b9)

(Information from statistics is duplicated in the experience bar for convenience)

Addition: at the moment {xp} is the number 0.5445623475645546. If it is possible to reduce the number of characters to 2 after 0, it would be great.

To get 0.54% for example, or remove 0 completely, making the fraction an integer. Something like this

   **{xp}%**

**Comment by Goblin-aka-Dark** [comment]
It was recommended to make 32 bit integer limit whatever that means

**Comment by Goblin-aka-Dark** [comment]
Conditional for the valuecontent
{# (playerxptonextlevel == 186791) ? '0' : playerxptonextlevel}

**Comment by s7092910** [comment]
So The CharacterFrameWindow Controller `{playerxptonextlevel}` will now display `Max Level` if the player is at the max level instead of repeating the last previous xp amount to the next level.

For the `{xp}` binding, you should be able to use `{# format('P2',xp)}`. That should format it to a percentage. So 0.5445623475645546 would become 54.46%. As `{xp}` is the percentage of fill between 0 to 1. So it wouldn't make sense to have that be displayed as 0.54%.
